[project]
name = "parallellm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=10.0.0",
    "polars>=1.32.3",
]

[tool.setuptools.packages.find]
include = ["parallellm*"]
